In [1]:
import torch
import numpy as np
import torch.nn as nn

In [2]:
features = torch.rand(50,4)*120
w = torch.rand(1,4,requires_grad=True)
b = torch.rand(1,requires_grad=True)

In [3]:
print(features,w,b)

tensor([[ 38.1090,  90.0748,  90.8044,  18.3203],
        [ 92.7394,  69.0846,  30.7332, 114.1033],
        [ 73.7445,  39.2405, 119.3159,  90.3881],
        [  8.8413,  19.1869,  14.4117, 110.3634],
        [ 63.8684,  21.0068,  91.3061,  82.1154],
        [ 76.3910,  48.7436,  63.3005,  52.8776],
        [ 63.8104, 118.8608,  28.5205,  54.3462],
        [ 97.0689,  14.8856,  95.1099,  10.0529],
        [ 87.0210,   8.0755,  88.9936,  15.9382],
        [ 35.5613, 103.3002, 104.5109,  11.6222],
        [ 88.5500,  59.2552, 119.2599,  55.6100],
        [107.6939,  86.7715,   4.3858, 101.8589],
        [ 38.8858,   7.8425,  17.3244, 109.3412],
        [ 84.2999,  86.2826, 102.3810,   1.1487],
        [115.7478,  56.7921,  42.1461,  79.9841],
        [ 55.5004,  27.8206, 117.5484,  37.1745],
        [ 26.2843,  64.7244,  86.8639,  92.6581],
        [ 30.8929,  49.4342,  73.3170,  87.0344],
        [ 38.9572,  56.9641,  36.1822,  74.6300],
        [111.2390,  74.3126,  91.8263,   6.6592],


In [4]:
def predict(x):
    return x@w.t() + b


In [5]:
labels = torch.rand(50,1,requires_grad=True)*120

In [6]:
from torch.utils.data import DataLoader, TensorDataset

In [61]:
train_dl = DataLoader(TensorDataset(features,labels),batch_size=10,shuffle=True)

In [62]:
for xb,yb in train_dl:
    print(xb,yb)
    break

tensor([[ 26.2843,  64.7244,  86.8639,  92.6581],
        [118.6360,  44.3396,  15.2182,  41.4432],
        [105.6982,   7.6371, 111.5433, 109.0484],
        [ 27.9934, 108.9191,  50.6395,  36.4942],
        [111.6541,  17.9614,  64.0358,   8.1599],
        [ 38.9572,  56.9641,  36.1822,  74.6300],
        [ 55.5004,  27.8206, 117.5484,  37.1745],
        [ 35.1571,  98.7212,  74.9190, 100.9136],
        [ 63.9649,  34.6863,  82.4672,  11.7473],
        [115.5546, 101.3658,   7.0112,  35.5973]]) tensor([[ 82.6320],
        [ 46.9363],
        [ 58.2107],
        [118.6289],
        [116.2744],
        [ 14.1163],
        [ 96.6851],
        [116.5484],
        [100.5326],
        [ 60.4271]], grad_fn=<StackBackward>)


In [63]:
def mse(preds,labels):
    return torch.sum((preds - labels)**2) / labels.numel()

In [64]:
for xb,yb in train_dl:
    print(mse(predict(xb),yb))
    break

tensor(1216.8040, grad_fn=<DivBackward0>)


In [65]:
for i in range(1,100):
    for xb,yb in train_dl:
        loss = mse(predict(xb),yb)
        print("Current loss:", loss)
        loss.backward(retain_graph=True)
        with torch.no_grad():
            w -= w.grad*(1e-6 + 0.33e-6)
            b -= b.grad*(1e-6 + 0.33e-6)
            w.grad.zero_()
            b.grad.zero_()



Current loss: tensor(2047.0511, grad_fn=<DivBackward0>)
Current loss: tensor(1672.8658, grad_fn=<DivBackward0>)
Current loss: tensor(1754.2574, grad_fn=<DivBackward0>)
Current loss: tensor(1256.1912, grad_fn=<DivBackward0>)
Current loss: tensor(667.2474, grad_fn=<DivBackward0>)
Current loss: tensor(1595.9707, grad_fn=<DivBackward0>)
Current loss: tensor(587.9731, grad_fn=<DivBackward0>)
Current loss: tensor(1247.2308, grad_fn=<DivBackward0>)
Current loss: tensor(1848.1205, grad_fn=<DivBackward0>)
Current loss: tensor(2129.0620, grad_fn=<DivBackward0>)
Current loss: tensor(2018.0305, grad_fn=<DivBackward0>)
Current loss: tensor(1272.8741, grad_fn=<DivBackward0>)
Current loss: tensor(1455.2590, grad_fn=<DivBackward0>)
Current loss: tensor(1520.7867, grad_fn=<DivBackward0>)
Current loss: tensor(1144.1022, grad_fn=<DivBackward0>)
Current loss: tensor(161.0210, grad_fn=<DivBackward0>)
Current loss: tensor(1640.2734, grad_fn=<DivBackward0>)
Current loss: tensor(1372.1296, grad_fn=<DivBackwar

Current loss: tensor(1103.9943, grad_fn=<DivBackward0>)
Current loss: tensor(1430.5782, grad_fn=<DivBackward0>)
Current loss: tensor(2523.8237, grad_fn=<DivBackward0>)
Current loss: tensor(993.8133, grad_fn=<DivBackward0>)
Current loss: tensor(1339.3043, grad_fn=<DivBackward0>)
Current loss: tensor(1164.7378, grad_fn=<DivBackward0>)
Current loss: tensor(714.8998, grad_fn=<DivBackward0>)
Current loss: tensor(1014.1268, grad_fn=<DivBackward0>)
Current loss: tensor(1941.5840, grad_fn=<DivBackward0>)
Current loss: tensor(2547.1860, grad_fn=<DivBackward0>)
Current loss: tensor(1488.1555, grad_fn=<DivBackward0>)
Current loss: tensor(947.3998, grad_fn=<DivBackward0>)
Current loss: tensor(2882.2090, grad_fn=<DivBackward0>)
Current loss: tensor(802.6046, grad_fn=<DivBackward0>)
Current loss: tensor(1281.0085, grad_fn=<DivBackward0>)
Current loss: tensor(1816.3480, grad_fn=<DivBackward0>)
Current loss: tensor(1168.8660, grad_fn=<DivBackward0>)
Current loss: tensor(1958.7340, grad_fn=<DivBackward

Current loss: tensor(1244.4089, grad_fn=<DivBackward0>)
Current loss: tensor(1311.8118, grad_fn=<DivBackward0>)
Current loss: tensor(2858.8208, grad_fn=<DivBackward0>)
Current loss: tensor(1693.9401, grad_fn=<DivBackward0>)
Current loss: tensor(1953.8264, grad_fn=<DivBackward0>)
Current loss: tensor(608.8199, grad_fn=<DivBackward0>)
Current loss: tensor(2069.9578, grad_fn=<DivBackward0>)
Current loss: tensor(1113.3176, grad_fn=<DivBackward0>)
Current loss: tensor(956.4987, grad_fn=<DivBackward0>)
Current loss: tensor(767.2760, grad_fn=<DivBackward0>)
Current loss: tensor(1176.2506, grad_fn=<DivBackward0>)
Current loss: tensor(1672.1140, grad_fn=<DivBackward0>)
Current loss: tensor(2814.3481, grad_fn=<DivBackward0>)
Current loss: tensor(1758.9854, grad_fn=<DivBackward0>)
Current loss: tensor(1505.8973, grad_fn=<DivBackward0>)
Current loss: tensor(1305.3732, grad_fn=<DivBackward0>)
Current loss: tensor(1627.0610, grad_fn=<DivBackward0>)
Current loss: tensor(1224.8226, grad_fn=<DivBackwar

In [66]:
w

tensor([[0.1608, 0.3106, 0.2730, 0.2446]], requires_grad=True)

In [67]:
b

tensor([0.6272], requires_grad=True)

In [68]:
mse(predict(features),labels)

tensor(1473.4438, grad_fn=<DivBackward0>)

In [29]:
predict(features)

tensor([[ 71.1467],
        [ 73.7750],
        [ 74.8082],
        [ 38.0850],
        [ 56.9486],
        [ 57.3658],
        [ 79.4585],
        [ 42.5002],
        [ 38.2386],
        [ 78.6963],
        [ 77.5767],
        [ 74.0891],
        [ 36.4943],
        [ 73.1126],
        [ 65.7903],
        [ 55.6153],
        [ 74.0700],
        [ 63.1083],
        [ 55.4947],
        [ 69.0890],
        [ 77.9949],
        [ 23.0145],
        [ 66.5776],
        [101.4803],
        [ 78.5243],
        [ 42.9344],
        [ 59.7977],
        [ 48.8378],
        [ 32.0090],
        [ 72.8252],
        [ 73.4272],
        [ 45.3590],
        [ 89.1609],
        [ 81.9410],
        [ 75.3084],
        [ 48.8374],
        [ 66.1421],
        [ 34.5902],
        [ 37.3489],
        [ 45.3720],
        [ 80.8592],
        [ 53.8935],
        [ 66.0559],
        [ 67.3999],
        [ 75.2827],
        [ 47.1565],
        [ 58.3038],
        [100.6986],
        [ 44.8285],
        [ 63.6141]],